spring:
  application:
    name: opptak-backend
  
  datasource:
    url: jdbc:postgresql://database:5432/opptak
    username: opptak_user
    password: opptak_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    no.opptak: DEBUG
    org.springframework.web: DEBUG